import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/DashboardSidebar";
import Header from "@/components/header";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div>
          <SidebarProvider open={false}>
            {/* <SidebarTrigger /> */}
            <AppSidebar />
            <div className="mt-[65px] w-full">
              {children}
            </div>
          </SidebarProvider>
        </div>
        <footer className="bg-gray-100 border-t border-gray-200 p-4 text-center text-sm text-gray-600">
          <p> &copy; {new Date().getFullYear()} StudioSwarm. All rights reserved.</p>
          <div className="mt-2">
            <Link href="#" className="hover:text-black">
              Terms of Service
            </Link>
            <span className="mx-2">|</span>
            <Link href="#" className="hover:text-black">
              Privacy Policy
            </Link>
            <span className="mx-2">|</span>
            <Link href="#" className="hover:text-black">
              Contact Us
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
